Algoritmo "Escolha"





Var

   voto : caractere

Inicio

   escreval("Digite seu voto: ")
   leia(voto)

   se voto ="20" entao
      escreval("Você votou em Fulano.")
   senao
      se voto ="30" entao
         escreval("Você votou em Beltrano.")
      senao
         se voto ="40" entao
            escreval("Você votou em Ciclano.")
         senao
            escreval("Voto nulo.")
         fimse
      fimse
   fimse

Fimalgoritmo
